In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import os
import datetime

today = datetime.datetime.now()
date = (f'{today.year}{str(today.month).zfill(2)}{str(today.day).zfill(2)}')

cos = ['삼성','롯데','현대차','신세계','SK','LG','네이버','카카오','GS','KT','CJ','넷마블','메타콩즈','bayc']
keywords = ['NFT','메타버스']

key_data = []
data = []

for co in cos:
    for keyword in keywords:
        if co =='bayc':
            keyword = ''
        url = f"https://search.naver.com/search.naver?where=news&query={co+keyword}&sm=tab_opt&sort=0&photo=0&field=0&pd=4&ds=&de=&docid=&related=0&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so%3Ar%2Cp%3A1d&is_sug_officeid=0"
        res = requests.get(url)
        res.raise_for_status()

        soup = BeautifulSoup(res.text,'lxml')
        titles = soup.find_all('a',attrs={'class':'news_tit'})

        for title in titles:
            if keyword in title.text:
                key_data.append([f'{co} {keyword}',title.text,title['href']])
            else:
                data.append([f'{co} {keyword}',title.text,title['href']])
df1 = pd.DataFrame(key_data,columns=['검색어','제목','URL'])
df2 = pd.DataFrame(data,columns=['검색어','제목','URL'])

In [2]:
df1

,검색어,제목,URL
0,삼성 NFT,클릭 한 번에 수백 번다는 NFT 소액 투자해봤더니... 7만원이 3만원으로 뚝,https://www.seoul.co.kr/news/newsView.php?id=2...
1,삼성 NFT,"유토피아추모관 우원기 회장, META-NFT KOREA 2022-초청 강연",http://www.breaknews.com/887192
2,삼성 메타버스,"포바이포, 이달 코스닥 입성… 메타버스·VR 시장 정조준",http://moneys.mt.co.kr/news/mwView.php?no=2022...
3,삼성 메타버스,[메타버스 날개 단 ESG] 메타버스로 영역 넓히는 ESG 경영,http://it.chosun.com/site/data/html_dir/2022/0...
4,삼성 메타버스,"메타버스 탑승한 포바이포, 이달 코스닥 입성",http://www.wowtv.co.kr/NewsCenter/News/Read?ar...
...,...,...,...
66,bayc,"리플 CEO ""SEC와의 긴 법정 다툼, 거의 마무리 단계"" 등",http://news.mk.co.kr/newsRead.php?no=337030&ye...
67,bayc,"NFT뱅크 ""메타버스 세상의 투자은행 될 것""",https://byline.network/?p=9004111222473017
68,bayc,“디지털 작품 단순 소유 더는 의미 없어…기능 있는 NFT 찾아야”,https://www.seoul.co.kr/news/newsView.php?id=2...
69,bayc,마케팅 효과 ‘굿’ 삼성·LG·게임회사 NFT 러시 속 들끓는 시장... NFT의 ...,https://www.seoul.co.kr/news/newsView.php?id=2...
70,bayc,NFT 가치창출·실용성 보고 투자… 초보는 직접 만들어 판매해 보기,https://www.seoul.co.kr/news/newsView.php?id=2...

In [3]:
df2

,검색어,제목,URL
0,삼성 NFT,"농업분야의 삼성전자, 테슬라들 [아침을 열며]",https://hankookilbo.com/News/Read/A20220414093...
1,삼성 NFT,[인터뷰] 정석문 코빗 리서치센터장 “비트코인 지금 안 사면 10년 뒤 후회…...,https://biz.chosun.com/stock/stock_general/202...
2,삼성 NFT,"네이버-카카오, 1분기 실적 인건비에 발목…반등 묘수는",https://www.dailian.co.kr/news/view/1103357/?s...
3,삼성 NFT,신한금융투자: 파라다이스·한세실업·한국항공우주,http://www.seoulfn.com/news/articleView.html?i...
4,삼성 NFT,"신세계 정용진·정유경 남매, '쌍둥이 승계' 디지털로 대통합",http://isplus.live.joins.com/news/article/arti...
...,...,...,...
104,넷마블 메타버스,"한화투자증권 “넷마블, 신작 출시 예정… 투자의견 ‘매수’”",http://www.fntimes.com/html/view.php?ud=202204...
105,넷마블 메타버스,"[이기자의 게임픽] 위메이드-넷마블-컴투스, 블록체인 게임 총력",https://zdnet.co.kr/view/?no=20220414112008
106,넷마블 메타버스,"안경덕 고용장관 ""장애인·비장애인 함께해야 가치있는 사회""",http://news.mt.co.kr/mtview.php?no=20220414144...
107,넷마블 메타버스,"한국장애인고용공단, '2022 장애인고용촉진대회' 개최…""가치 모아 내일로""",http://www.cstimes.com/news/articleView.html?i...
108,메타콩즈 메타버스,"메타콩즈x싸이더스스튜디오엑스 MOU 체결, 로지 활용 PFP NFT 개발 및 마케팅...",http://www.stardailynews.co.kr/news/articleVie...

In [4]:
with pd.ExcelWriter(f'{date}.xlsx') as w:
    df1.to_excel(w,sheet_name='주요 기사')
    df2.to_excel(w,sheet_name='그 외 기사')